import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api } from "../services/api";
import { toast } from "sonner"; // Assuming sonner or similar is used

export const ReportPage = () => {
  const { reportId } = useParams();
  
  const { data: report, isLoading, error } = useQuery({
    queryKey: ['report', reportId],
    queryFn: () => api.get(`/reports/${reportId}`).then(res => res.data)
  });

  if (isLoading) return <div className="p-20 text-center">Loading report...</div>;
  if (error || !report) return <div className="p-20 text-center text-rose">Report not found.</div>;

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Link copied!");
  };

  return (
    <div className="bg-white p-8 print:p-0">
      <div className="flex justify-between print:hidden mb-8">
        <button onClick={handleShare} className="px-4 py-2 border rounded">Share</button>
        <button onClick={() => window.print()} className="px-4 py-2 border rounded bg-signal text-white">Print</button>
      </div>

      <header className="mb-10">
        <h1 className="text-3xl font-bold">{report.sourceFile}</h1>
        <p className="text-zinc-500">Generated on: {new Date(report.createdAt).toLocaleDateString()}</p>
      </header>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Performance Score</h2>
        <div className="p-6 bg-cloud rounded-lg text-center">
            <div className="text-6xl font-bold text-signal">{report.performanceScore}</div>
            <p className="text-xl font-medium">{report.grade}</p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Executive Summary</h2>
        <p className="text-zinc-700 leading-relaxed">{report.summary || "Account is performing within expected benchmarks."}</p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Critical Issues</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr className="border-b bg-zinc-50 text-left">
              <th className="p-3">Issue</th>
              <th className="p-3">Campaign</th>
            </tr>
          </thead>
          <tbody>
            {(report.diagnostics || []).filter(d => d.severity === 'critical').map((d, i) => (
              <tr key={i} className="border-b">
                <td className="p-3">{d.description}</td>
                <td className="p-3">{d.affectedEntity}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">Top Recommendations</h2>
        <ul className="space-y-4">
          {(report.aiRecommendations || []).slice(0, 5).map((rec, i) => (
            <li key={i} className="p-4 border rounded">
                <h4 className="font-semibold">{rec.title}</h4>
                <p className="text-sm text-zinc-600">{rec.description}</p>
            </li>
          ))}
        </ul>
      </section>

      <footer className="mt-20 pt-10 border-t text-center text-zinc-400 text-sm">
        Generated by AdsPulse · adspulse.io
      </footer>
    </div>
  );
};
